/* SecureFileException.cs
 * 
 * PROGRAMMER:    Jeffrey T. Darlington
 * DATE:          September 17, 2009
 * PROJECT:       Cryptnos
 * .NET VERSION:  2.0
 * REQUIRES:      See using statements; all are .NET internal System objects.
 * REQUIRED BY:   SecureFile.cs
 *
 * A simple derivative of System.Exception, this class represents all possible errors that may
 * be generated by using one of the SecureFile methods.  It find out why the exception was
 * thrown, make sure to catch these exceptions and use the Message property.
 * 
 * This program is Copyright 2009, Jeffrey T. Darlington.
 * E-mail:  jeff@cryptnos.com
 * Web:     http://www.cryptnos.com/
 * 
 * This program is free software; you can redistribute it and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See theGNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program;
 * if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */
using System;
using System.Collections.Generic;
using System.Text;

namespace com.gpfcomics.Cryptnos
{
    /// <summary>
    /// A sub-class of Exception that defines issues specific to the <see cref="SecureFile"/>
    /// class
    /// </summary>
    public class SecureFileException : Exception
    {
        /// <summary>
        /// Creates an exception with a specific message
        /// </summary>
        /// <param name="message">The message</param>
        public SecureFileException(string message) : base(message)
        {
        }

        /// <summary>
        /// Creates a exception with a default message
        /// </summary>
        public SecureFileException() :
            base("An unspecified error occurred while reading or writing a secure file.")
        {
        }
    }
}
