/* ImportHandlerException.cs
 * 
 * PROGRAMMER:    Jeffrey T. Darlington
 * DATE:          April 28, 2010
 * PROJECT:       Cryptnos
 * .NET VERSION:  2.0
 * REQUIRES:      See using statements
 * REQUIRED BY:   Form1
 * 
 * This subclass of System.Exception is thrown by specific errors when importing a Cryptnos
 * export file using ImportExportHandler.ImportFromFile().  The messages generated by this
 * exception should be suitable for displaying directly to the user, so each time you use
 * ImportExportHandler, make sure to catch this exception specifically before catching any
 * other exception.
 * 
 * This program is Copyright 2010, Jeffrey T. Darlington.
 * E-mail:  jeff@cryptnos.com
 * Web:     http://www.cryptnos.com/
 * 
 * This program is free software; you can redistribute it and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See theGNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with this program;
 * if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */
using System;
using System.Collections.Generic;
using System.Text;

namespace com.gpfcomics.Cryptnos
{
    /// <summary>
    /// This subclass of <see cref="Exception"/> is used by the <see cref="ImportExportHandler"/>
    /// to denote specific errors when trying to read and parse an export file containing
    /// Cryptnos <see cref="SiteParameters"/>.
    /// </summary>
    public class ImportHandlerException : Exception
    {
        public ImportHandlerException(string message) : base(message)
        {
        }

        public ImportHandlerException() :
            base("An unexpected error has occurred while trying to read the specified " +
            "Cryptnos export file.")
        {
        }
    }
}
